DROP DOMAIN IF EXISTS int53 CASCADE;
CREATE DOMAIN int53 AS bigint
    CHECK (VALUE > -9007199254740991 AND VALUE < 9007199254740992); -- 2^53

DROP TABLE IF EXISTS messages_t CASCADE;
CREATE TABLE messages_t (
    id int53 PRIMARY KEY,
    content TEXT NOT NULL,
    role VARCHAR(255) NOT NULL,
    "parentId" int53 NOT NULL,
    author VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    "userId" int53 NOT NULL,
    streaming BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" int53 NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
    tablab VARCHAR(255) NOT NULL DEFAULT '?'
);

-- ALTER TABLE messages_t ADD COLUMN tablab VARCHAR(255) NOT NULL DEFAULT '?';

DROP TABLE IF EXISTS users_t CASCADE;
CREATE TABLE users_t (
    id int53 PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    "passwordHash" VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL
);
